---
driver_plugin: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[rightscale_tag]
  - recipe[rightscale_tag::monitoring]
  attributes:
    rightscale:
      instance_uuid: 01-ABCDEFG123456
    cloud:
      provider: vagrant
      public_ips:
      - null
      - ""
      - 33.33.33.10
      private_ips:
      - null
      - ""
      - 10.0.2.15

# Application server tests
- name: application
  run_list:
  - recipe[rightscale_tag]
  - recipe[rightscale_tag::monitoring]
  - recipe[fake::app_server]
  attributes:
    rightscale:
      instance_uuid: 02-BBCDEFG123457
    cloud:
      provider: vagrant
      public_ips:
      - null
      - ""
      - 33.33.33.10
      private_ips:
      - null
      - ""
      - 10.0.2.15

# Database server tests
- name: database
  run_list:
  - recipe[rightscale_tag]
  - recipe[rightscale_tag::monitoring]
  - recipe[fake::db_server]
  attributes:
    rightscale:
      instance_uuid: 03-CBCDEFG123458
    cloud:
      provider: vagrant
      public_ips:
      - null
      - ""
      - 33.33.33.12
      private_ips:
      - null
      - ""
      - 10.0.2.17

# Load Balancer server tests
- name: load_balancer
  run_list:
  - recipe[rightscale_tag]
  - recipe[rightscale_tag::monitoring]
  - recipe[fake::lb_server]
  attributes:
    rightscale:
      instance_uuid: 04-DBCDEFG123459
    cloud:
      provider: vagrant
      public_ips:
      - null
      - ""
      - 33.33.33.11
      private_ips:
      - null
      - ""
      - 10.0.2.16
