---
driver_plugin: vagrant

provisioner:
  name: chef_solo

platforms:

- name: centos-7.0
  driver_config:
    box: opscode-centos-7.0
- name: rhel-6.5
  driver_config:
    box: local-rhel-6.5
    box_url: file://<%= File.expand_path('~') %>/opscode_rhel-6.5_chef-provisionerless.box
- name: rhel-7.0
  driver_config:
    box: local-rhel-7.0
    box_url: file://<%= File.expand_path('~') %>/opscode_rhel-7.0_chef-provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[rightscale_tag]
  - recipe[rightscale_tag::monitoring]
  attributes:
    rightscale:
      instance_uuid: 01-ABCDEFG123456
    cloud:
      provider: vagrant
      public_ips:
      - null
      - ""
      - 33.33.33.10
      private_ips:
      - null
      - ""
      - 10.0.2.15

# Load Balancer server tests
- name: load_balancer
  run_list:
  - recipe[rightscale_tag]
  - recipe[fake::load_balancer]
  attributes:
    rightscale:
      instance_uuid: 04-DBCDEFG123459
    cloud:
      provider: vagrant
      public_ips: ['33.33.33.11']
      private_ips: ['10.0.2.16']

# Application server tests
- name: application
  run_list:
  - recipe[rightscale_tag]
  - recipe[fake::application]
  attributes:
    rightscale:
      instance_uuid: 02-BBCDEFG123457
    cloud:
      provider: vagrant
      public_ips: ['33.33.33.10']
      private_ips: ['10.0.2.15']

# Database server tests
- name: database
  run_list:
  - recipe[rightscale_tag]
  - recipe[fake::database]
  attributes:
    rightscale:
      instance_uuid: 03-CBCDEFG123458
    cloud:
      provider: vagrant
      public_ips: ['33.33.33.12']
      private_ips: ['10.0.2.17']
